package gui.components;
import javax.swing.table.AbstractTableModel;
import java.util.List;
import models.Card;

public class CardTableModel extends AbstractTableModel {
    // class generated by chat gpt
    private final List<Card> cards;
    private final String[] columnNames = {"Card Name", "Language", "Foil", "Condition"};

    public CardTableModel(List<Card> cards) {
        this.cards = cards;
    }

    @Override
    public int getRowCount() {
        return cards.size();
    }

    @Override
    public int getColumnCount() {
        return columnNames.length;
    }

    @Override
    public String getColumnName(int column) {
        return columnNames[column];
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        Card card = cards.get(rowIndex);
        switch (columnIndex) {
            case 0: return card.getCardName();
            case 1: return card.getLanguage();
            case 2: return card.isFoil();
            case 3: return card.getCondition();
            default: return null;
        }
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
        switch (columnIndex) {
            case 2: return Boolean.class;
            default: return String.class;
        }
    }
}
