package gui.components;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
// class generated by ChatGPT
public class ChooseFilePanel extends JPanel {

    private JTextField fileField;
    private JButton chooseFileButton;
    private JButton openButton;
    private JLabel infoLabel;
    
    public ChooseFilePanel() {
        setLayout(new BorderLayout());
        
        // Initialize components
        fileField = new JTextField(20);
        chooseFileButton = new JButton("Choose File...");
        openButton = new JButton("Open File");
        infoLabel = new JLabel("Please select a file:");
        
        // Set up file chooser button action
        chooseFileButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chooseFileActionPerformed();
            }
        });
        
        // Set up open button action
        openButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openFileActionPerformed();
            }
        });

        // Set up panel layout
        JPanel filePanel = new JPanel();
        filePanel.setLayout(new BorderLayout());
        filePanel.add(fileField, BorderLayout.CENTER);
        filePanel.add(chooseFileButton, BorderLayout.EAST);

        // Add components to main panel
        add(infoLabel, BorderLayout.NORTH);
        add(filePanel, BorderLayout.CENTER);
        add(openButton, BorderLayout.SOUTH);
    }
    
    private void chooseFileActionPerformed() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            fileField.setText(selectedFile.getAbsolutePath());
        }
    }
    
    private void openFileActionPerformed() {
        String filePath = fileField.getText();
        if (filePath.isEmpty()) {
            // Handle case when no file is selected
            System.out.println("No file selected.");
        } else {
            File file = new File(filePath);
            if (file.exists() && file.isFile()) {
                // Perform your action with the selected file
                System.out.println("File selected: " + filePath);
            } else {
                // Handle case when the selected file does not exist
                System.out.println("Selected file does not exist.");
            }
        }
    }
    

}