/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui.components;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class QuitButton extends JButton {
//class generated by chat gpt
    public QuitButton() {
        super("Quit Application");

        // Add an ActionListener to handle button clicks
        addActionListener((ActionEvent e) -> {
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?", "Quit Application", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Exit the application
                JFrame frame = (JFrame) getTopLevelAncestor();
                frame.dispose(); // Close the JFrame
                System.exit(0); // Exit the application
            }
        });
    }


}

