/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui.navigationpanels;

import com.mycompany.mtgCardManager.MtgCardManager;
import fileio.CSVCardReader;
import groupmanager.DerbyCollectionsManager;
import gui.MainMenu;

import gui.basePanels.UploadsPanel;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.CollectionList;
import models.Deck;

/**
 *
 * @author User
 */
// took the class generated by cgatgpt in ChooseFolderPanel and edited it
public class ImportListPanel extends UploadsPanel {

    private final JTextField fileField;
    private final JTextField nameField;
    private final JButton chooseFolderButton;
    private final JButton saveButton;
    JPanel main = this.getMainPanel();

    public ImportListPanel() {

        JPanel folderPanel = new JPanel(new FlowLayout());
        JLabel folderLabel = new JLabel("Folder:");
        fileField = new JTextField(20);
        chooseFolderButton = new JButton("Choose...");
        chooseFolderButton.addActionListener((ActionEvent e) -> {
            chooseFolderActionPerformed(e);
        });
        folderPanel.add(folderLabel);
        folderPanel.add(fileField);
        folderPanel.add(chooseFolderButton);

        JPanel filePanel = new JPanel(new FlowLayout());
        JLabel fileLabel = new JLabel("File Name:");
        nameField = new JTextField(20);
        filePanel.add(fileLabel);
        filePanel.add(nameField);

        saveButton = new JButton("Select Folder");
        saveButton.addActionListener((ActionEvent e) -> {
            setFields(e);
        });

        // Add components to panel
        main.setLayout(new FlowLayout());
        main.add(folderPanel);
        main.add(filePanel);
        main.add(saveButton);
    }

    private void chooseFolderActionPerformed(ActionEvent e) {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files", "csv");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = chooser.getSelectedFile();
            fileField.setText(selectedFolder.getAbsolutePath());
        }
    }

    private void setFields(ActionEvent e) {
        String path = fileField.getText();
        String name = nameField.getText();

        if (path.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No file selected.");
            return;
        } else if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No name entered.");
        }

        File file = new File(path);
        if (file.exists() && file.isFile() && file.getName().endsWith(".csv")) {
            try {
                // Perform your action with the selected file and name
                System.out.println("CSV file selected: " + path);
                System.out.println("Name entered: " + name);
                CSVCardReader reader = new CSVCardReader(path);
                CollectionList list = reader.readListFromFile(name);
                DerbyCollectionsManager manager = MtgCardManager.collections;
                manager.saveList(list);
                JOptionPane.showMessageDialog(this, "Operation Complete.");
                JPanel returnPanel = new MainMenu();
                MtgCardManager.menu.navigate_to_panel(returnPanel);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "There is a problem with the formatting of the CSV file.");
                Logger.getLogger(ImportListPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "There is a problem adding the list to the database");
                Logger.getLogger(ImportListPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selected file is not a valid CSV file.");
        }

    }

}
